### ISSUE TITLE
PrimaryScrollController Support

### ISSUE THREAD

**Issue by clragon** [NamanShergill/flutter_scroll_to_top#6]
Currently, the ScrollWrapper explicitly demands a `ScrollController`.

However, Flutter has this mechanic where it uses inherited widgets to pass a `ScrollController` through the widget tree by `context`.
`ListView` and cohorts use this when `primary` is `true` and no `ScrollController` is passed.

I feel like it would be nice to implement this here, 
because it could result in not having to pass a `ScrollController` to neither the `ScrollWrapper` nor the `ListView`.

The [`PrimaryScrollController`](https://api.flutter.dev/flutter/widgets/PrimaryScrollController-class.html) is documented and the exact usage is seen in the framework in [`scroll_view.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scroll_view.dart#L391)

**Comment by NamanShergill** [comment]
So basically, a bool parameter `primary` and an assert check for primary either being false or the scroll controller being null just like in your link is what you're suggesting?

I think that would work, but there's the issue of if someone forgets to pass off the scroll controller even if `primary` isn't set to true. I could add an assert for that like in your link, but the scroll controller being passed in that scenario is very essential and I don't think making it nullable is the best approach. Maybe having a constructor like `ScrollWrapper.primary` might be a better approach?

**Comment by NamanShergill** [comment]
Or if a dev knows about this implementation and wants the behaviour, they could also just pass `PrimaryScrollController.of(context)` to the scroll controller parameter in the current widget, no? Should the widget really handle this on its own?

**Comment by clragon** [comment]
Afaik, widgets like `Scaffold` already provide a `PrimaryScrollController`, so it being available is close to being guaranteed.

Other libraries like `pull_to_refresh` also implement this, because it makes the code just a tiny bit shorter and nicer;
For example, no `StatefulWidget` with a variable for the `ScrollController` has to be created just to accommodate for the `ScrollController` by itself.
Personally I think its really nice, I can also try implementing it and make a PR, if you'd like that.

**Comment by NamanShergill** [comment]
> Afaik, widgets like `Scaffold` already provide a `PrimaryScrollController`, so it being available is close to being guaranteed.
> 
> Other libraries like `pull_to_refresh` also implement this, because it makes the code just a tiny bit nicer; Personally I think its really cool, I can also try implementing it and make a PR, if you'd like that.

I got that but I'm talking about a different concern, about making the scroll controller parameter nullable (and it using the PrimaryScrollController for that scenario) doesn't seem like the best approach to me when list views etc have the primary property to be false by default. That could lead to someone using the widget without providing the scroll controller, not understanding why it's not working for a child list view which has `primary` set to false.

All of this seems to be fixed by just passing off `PrimaryScrollController.of(context)` in the scroll controller parameter in the current widget for the use case you mentioned.

**Comment by clragon** [comment]
ah I see.
But `ListView` do not actually have `primary` set to `false` by default.

In the [source code](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scroll_view.dart#L111) we can see it is actually this condition

```dart
primary = primary ?? controller == null && identical(scrollDirection, Axis.vertical),
```

**Comment by NamanShergill** [comment]
Hmm, you're right.
I'll make the field nullable. The only scenario I can see causing issues is if someone passes off a controller for the child scrollable but not to the wrapper, but I think clearing that requirement up in the documentation should be enough for that.

**Comment by NamanShergill** [comment]
You know, I'm starting to think that maybe I should scrap the `child` parameter from the widget entirely and replace it with a `builder` parameter that just gives you the scrollcontroller the wrapper is using to pass off to the child. That would solve the issue of someone potentially causing the conflicting behaviour I mentioned above.

**Comment by NamanShergill** [comment]
That being said I would also have to account for the scroll direction before adding the primary scroll controller behaviour. I'll make a release with the PR you made tomorrow and work on this over the weekend.

**Comment by clragon** [comment]
The `builder` would definitely be an option, but then you cant take advantage of all the fancy primary scroll controllers.

Regardless, do you want me to make a PR for #3 or did you plan on looking into that on the weekend as well?

**Comment by NamanShergill** [comment]
> The `builder` would definitely be an option, but then you cant take advantage of all the fancy primary scroll controllers.

The ScrollWrapper widget would still have a nullable scroll controller parameter. If one is provided, that is the one that the builder will pass on, if it isn't, it'll pass off a `PrimaryScrollController.of(context)` if the scroll direction is vertical, and a null value otherwise. I just have to check if there will be any conflicts with NestedScrollViews if I do this.

> Regardless, do you want me to make a PR for #3 or did you plan on looking into that on the weekend as well?

I think I'll include them both when I make the changes. This one should be fairly simple, an enum with two modes for using the notification listener or the scroll controller with a warning for NestedScrollViews in the documentation.

**Comment by clragon** [comment]
> That would solve the issue of someone potentially causing any conflicting behaviour like I mentioned above.

Only if the person then also actually uses the passed in scroll controller.
Which wouldnt be necessary if theyre using for example a `ListView` which will also just pull the `PrimaryScrollController`.

It probably makes it more obvious though.

**Comment by NamanShergill** [comment]
> > That would solve the issue of someone potentially causing any conflicting behaviour like I mentioned above.
> 
> Only if the person then also actually uses the passed in scroll controller. Which wouldnt be necessary if theyre using for example a `ListView` which will also just pull the `PrimaryScrollController`.
> 
> It probably makes it more obvious though.

Yes, I just want to make it clearer what exactly is happening here and make the code a bit more readable for someone using the widget.

**Comment by NamanShergill** [comment]
Considering NestedScrollView sets up a [Primary controller for its children to use](https://github.com/flutter/flutter/blob/18116933e77adc82f80866c928266a5b4f1ed645/packages/flutter/lib/src/widgets/nested_scroll_view.dart#L497), I could completely remove the Notification listener implementation entirely and listen to the scrollcontroller for the offset as suggested in #3.

However, that might mean pressing the prompt means it only scrolls to the top of the inner scrollable and not the whole NestedScrollView like it does currently, but that seems like better behaviour, UX wise.

**Comment by NamanShergill** [comment]
@clragon Thank you bringing `PrimaryScrollController` to my attention it helped fix most of the open issues currently
