### ISSUE TITLE
Floating Button Behaviour

### ISSUE THREAD

**Issue by clragon** [NamanShergill/flutter_scroll_to_top#7]
The scroll to top button currently appears at a fixed scroll off-set.

I would be very interested in a behaviour similar to the `SliverAppBar` with `floating: true`,
where the button would only appear if the user is scrolling up.

(I also hope I am not too annoying with all the requests)

**Comment by NamanShergill** [comment]
Hmm, how do you think that should be implemented? Would a gesture detector detecting a scroll up be enough?

**Comment by NamanShergill** [comment]
> (I also hope I am not too annoying with all the requests)

No please, any feature requests to improve the library are welcome!

**Comment by clragon** [comment]
> Would a gesture detector detecting a scroll up be enough?

Probably? I tried looking at how the slivers do it in the source code, but its convoluted, so I didnt figure it out.

**Comment by NamanShergill** [comment]
@clragon can you check out #8 if that is the implementation you are looking for?

**Comment by clragon** [comment]
oh yeah this is brilliant.

I was thinking it might even be nice to have a small off-set that the user has to scroll up before it shows up,
(which could be configured, like the `promptScrollOffset`)
but that might complicate the implementation alot.

**Comment by NamanShergill** [comment]
> oh yeah this is brilliant.
> 
> I was thinking it might even be nice to have a small off-set that the user has to scroll up before it shows up, (which could be configured, like the `promptScrollOffset`) but that might complicate the implementation alot.

yeah, it will be hard to account for all the edge cases. I will release this implementation for now and update it later if I can think of a consistent way to implement that

**Comment by clragon** [comment]
maybe something like tracking the point at which the user first started scrolling up (when the scroll notification gets triggered) and whenever the user scrolls we compare it to the offset.
when a down-scrolling notification occurs, we simply set the point of first scrolling up to null again.

**Comment by NamanShergill** [comment]
@clragon Added in the PR, is that what you required?

Also I am having trouble with the parameter names being clear with their purpose so if you think they should be renamed to something else please let me know

**Comment by clragon** [comment]
this works wonderfully!
I dont think I can come up with any better names.

Though I think the doc string for `scrollOffsetUntilVisible` is incorrect?

```dart
If alwaysVisibleAtOffset is true, what offset should the user scroll in the opposite direction (ex, upwards scroll on a non-reversed vertical ScrollView) before the prompt becomes visible.
```

doesnt this only trigger when `alwaysVisibleAtOffset` is `false`?

**Comment by NamanShergill** [comment]
Right, I'll fix that

**Comment by clragon** [comment]
it also seems that the button will not show up in a `NestedScrollView`, if `alwaysVisibleAtOffset` is false.

**Comment by NamanShergill** [comment]
> it also seems that the button will not show up in a `NestedScrollView`, if `alwaysVisibleAtOffset` is false, and a scrollcontroller is passed to both the `NestedScrollView` and the `ScrollWrapper`.
> 
> I assume thats because of how the `NestedScrollView` works.

It's working fine for me, did you add `NestedScrollView.sliverOverlapAbsorberHandleFor(context);` to handle the overlap between the header and body, in a builder function inside the body? It's possible that it is showing up but is hidden behind the header due to the overlap

**Comment by NamanShergill** [comment]
Ah, wait.

The issue here is you are not supposed to pass a scroll controller in that case @clragon 
That is how it works with ScrollViews inside the body of NestedScrollView, they are supposed to use the PrimaryScrollController

**Comment by clragon** [comment]
ah, I see. Yeah, I kind of suspected that.

**Comment by NamanShergill** [comment]
If you pass a scroll controller to a CustomScrollView without using the ScrollWrapper you will face a similar issue, where the CustomScrollView  will start scrolling free from the NestedScrollView

**Comment by NamanShergill** [comment]
I will add a warning in the readme for this

**Comment by NamanShergill** [comment]
The new version is up on pub.dev

**Comment by clragon** [comment]
very nice 👌
