### ISSUE TITLE
scroll to bottom

### ISSUE THREAD

**Issue by clragon** [NamanShergill/flutter_scroll_to_top#9]
I saw the package now supports both vertical and horizontal axis, which is very nice.

It might be cool to have the option to pass the `reverse` boolean,
which listviews etc also have,
which makes the listview scroll to up instead of down.

The package as is works fine, if the scrollview is reversed, but the button is misplaced.

Now this isnt a feature that I personally would need, but I could imagine chat apps enjoying that.
Apps like discord have a button like this one, it is simply located at the bottom, pointing down.

Then again, their button also triggers something more than simply scrolling to the bottom, because of searching and inserting the user into the scrollview somewhere in the middle of nowhere etc... 
(maybe there could even be a `VoidCallback` that is called when scrolling back?)

**Comment by NamanShergill** [comment]
Do you mean basically changing the alignment of the button on reversed lists?

I don't want to give it too many params that will be common with the child ScrollView as that means I would need to pass it in the builder callback for consistency.

However, considering I am currently passing the context, scrollController, scrollDirection to the builder, I can replace the last one with a properties class that contains such props the child would have common with, how does that sound?

> (maybe there could even be a VoidCallback that is called when scrolling back?)
You mean a callback for when the prompt is pressed?

**Comment by clragon** [comment]
that doesnt sound too bad.
theres definitely an issue with passing too many parameters and the code becoming unberably long.

if you add something like `ScrollWrapperConfig`, that ought to do it.
maybe it could even contain the scrollcontroller, since we only need it half the time.

**Comment by NamanShergill** [comment]
> that doesnt sound too bad. theres definitely an issue with passing too many parameters and the code becoming unberably long.
> 
> if you add something like `ScrollWrapperConfig`, that ought to do it. maybe it could even contain the scrollcontroller, since we only need it half the time.

okay, I will add a `ScrollViewProperties` class for this and move the scroll controller to it as well

**Comment by NamanShergill** [comment]
> (maybe there could even be a VoidCallback that is called when scrolling back?)

You mean a simple callback for when the prompt is pressed for this?

**Comment by clragon** [comment]
> You mean a simple callback for when the prompt is pressed for this?

yep, pretty much!

**Comment by NamanShergill** [comment]
Added both in the  PR.

Will start updating the Readme now, please let me know if you have any more inputs!

**Comment by clragon** [comment]
works very well!
